name: publish
on:
  pull_request:
    types: [closed]
    branches:
      - master
      - dev
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          #cache: 'yarn'
      
      - name: Version and Yarn publish
      
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
